### 11. Faça uma análise dos filmes e mostre para o investidor uma análise gerencial dos filmes no dataset (análise livre para mostrar sua criatividade, desenvolvimento e habilidades do Python).

In [1]:
import pandas as pd

In [20]:
#Importando arquivo:
title_names = pd.read_csv('Arquivos/title_names.tsv', sep='\t')

C:\Users\Jump Label\AppData\Local\Temp\ipykernel_18324\3930741.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  title_names = pd.read_csv('Arquivos/title_names.tsv', sep='\t')

In [22]:
#Importando arquivo:
ratings = pd.read_csv('Arquivos/t_ratings.tsv',sep='\t')

In [23]:
#Fazendo a junção das tabelas:
juncao = pd.merge(title_names,ratings, on= 'tconst', how='left')

In [24]:
#Filtrando para aparecer somente a categoria de filmes:
juncao = juncao[juncao['titleType']=='movie']

In [42]:
#Vizualizar resultado com os 60 primeiros:
juncao.head(60)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
498,tt0000502,movie,Bohemios,Bohemios,0,1905,\N,100,\N,4.4,15.0
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70,"Action,Adventure,Biography",6.1,744.0
587,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907,\N,90,Drama,5.0,17.0
610,tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907,\N,0,Drama,4.5,24.0
625,tt0000630,movie,Hamlet,Amleto,0,1908,\N,0,Drama,3.9,25.0
668,tt0000675,movie,Don Quijote,Don Quijote,0,1908,\N,0,Drama,4.7,20.0
672,tt0000679,movie,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908,\N,120,"Adventure,Fantasy",5.3,66.0
729,tt0000739,movie,El pastorcito de Torrente,El pastorcito de Torrente,0,1908,\N,0,Drama,6.0,17.0
783,tt0000793,movie,Andreas Hofer,Andreas Hofer,0,1909,\N,0,Drama,4.6,21.0
804,tt0000814,movie,La bocana de Mar Chica,La bocana de Mar Chica,0,1909,\N,0,\N,NaN,NaN
828,tt0000838,movie,A Cultura do Cacau,A Cultura do Cacau,0,1909,\N,0,\N,NaN,NaN
832,tt0000842,movie,De Garraf a Barcelona,De Garraf a Barcelona,0,1909,\N,0,\N,6.6,10.0
836,tt0000846,movie,Un día en Xochimilco,Un día en Xochimilco,0,1909,\N,0,\N,NaN,NaN
840,tt0000850,movie,Los dos hermanos,Los dos hermanos,0,1909,\N,0,\N,NaN,NaN
849,tt0000859,movie,Fabricación del corcho en Sant Feliu de Guixols,Fabricación del corcho en Sant Feliu de Guixols,0,1909,\N,0,\N,NaN,NaN
852,tt0000862,movie,Faldgruben,Faldgruben,0,1909,\N,0,\N,5.1,17.0
857,tt0000867,movie,Fiesta de toros,Fiesta de toros,0,1909,\N,0,\N,NaN,NaN
858,tt0000868,movie,Fiestas de Santa Lucía - Belenes,Fiestas de Santa Lucía - Belenes,0,1909,\N,0,\N,NaN,NaN
859,tt0000869,movie,Fiestas en La Garriga,Fiestas en La Garriga,0,1909,\N,0,\N,NaN,NaN
869,tt0000879,movie,Gira política de Madero y Pino Suárez,Gira política de Madero y Pino Suárez,0,1909,\N,0,\N,NaN,NaN
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,\N,0,Drama,4.7,38.0
930,tt0000941,movie,Locura de amor,Locura de amor,0,1909,\N,0,Drama,4.8,24.0
936,tt0000947,movie,Lægens offer,Lægens offer,0,1909,\N,0,\N,NaN,NaN
948,tt0000959,movie,Melilla y el Gurugu,Melilla y el Gurugu,0,1909,\N,0,\N,4.4,11.0
972,tt0000984,movie,Niños en la alameda,Niños en la alameda,0,1909,\N,0,\N,4.8,10.0
980,tt0000992,movie,De onde Veje,De onde Veje,0,1909,\N,0,\N,4.5,17.0
995,tt0001007,movie,La primera y segunda casetas,La primera y segunda casetas,0,1909,\N,0,\N,5.0,10.0
998,tt0001010,movie,Protección de un convoy de víveres en el puent...,Protección de un convoy de víveres en el puent...,0,1909,\N,0,\N,4.1,15.0
1016,tt0001028,movie,Salome Mad,Salome Mad,0,1909,\N,0,Comedy,4.4,18.0
1026,tt0001038,movie,Sherlock Holmes VI,Sherlock Holmes VI,0,1910,\N,0,\N,3.8,22.0
1031,tt0001043,movie,Smith's Knockabout Theatre,Smith's Knockabout Theatre,0,1909,\N,0,\N,NaN,NaN
1037,tt0001049,movie,Gøngehøvdingen,Gøngehøvdingen,0,1909,\N,0,"Drama,War",4.0,17.0
1039,tt0001051,movie,El sueño milagroso,El sueño milagroso,0,1909,\N,0,\N,4.6,10.0
1047,tt0001059,movie,O Terremoto de Benavente,O Terremoto de Benavente,0,1909,\N,0,Documentary,NaN,NaN
1057,tt0001069,movie,Toma del Gurugu,Toma del Gurugu,0,1909,\N,0,\N,4.4,10.0
1068,tt0001080,movie,Two of the Boys,Two of the Boys,0,1909,\N,0,\N,NaN,NaN
1069,tt0001081,movie,La vida en el campamento,La vida en el campamento,0,1909,\N,0,\N,NaN,NaN
1070,tt0001082,movie,Viernes de dolores,Viernes de dolores,0,1909,\N,0,\N,NaN,NaN
1089,tt0001101,movie,Abraham Lincoln's Clemency,Abraham Lincoln's Clemency,0,1910,\N,0,\N,5.1,38.0
1097,tt0001109,movie,L'aluminite,L'aluminite,0,1910,\N,0,\N,NaN,NaN
1100,tt0001112,movie,Amleto,Amleto,0,1910,\N,0,Drama,3.8,40.0
1101,tt0001113,movie,Amor gitano,Amor gitano,0,1910,\N,0,\N,5.0,17.0
1103,tt0001115,movie,Ansigttyven I,Ansigttyven I,0,1910,\N,0,Crime,4.6,20.0
1104,tt0001116,movie,Ansigttyven II,Ansigttyven II,0,1910,\N,0,\N,4.6,19.0
1110,tt0001122,movie,The Red Inn,L'auberge rouge,0,1910,\N,0,\N,5.1,19.0
1129,tt0001141,movie,The Butterfly,The Butterfly,0,1910,\N,0,\N,NaN,NaN
1130,tt0001142,movie,By Order of Napoleon,By Order of Napoleon,0,1910,\N,0,\N,NaN,NaN
1135,tt0001147,movie,O Centenário da Guerra Peninsular,O Centenário da Guerra Peninsular,0,1910,\N,0,Documentary,NaN,NaN
1147,tt0001159,movie,The Connecticut Yankee,The Connecticut Yankee,0,1910,\N,0,\N,5.4,29.0
1151,tt0001163,movie,Corrida da Rampa,Corrida da Rampa,0,1910,\N,0,Documentary,NaN,NaN
1163,tt0001175,movie,Camille,La dame aux camélias,0,1912,\N,0,"Drama,Romance",5.8,36.0
1167,tt0001179,movie,Desfile histórico del centenario,Desfile histórico del centenario,0,1910,\N,0,\N,NaN,NaN
1172,tt0001184,movie,Don Juan de Serrallonga,Don Juan de Serrallonga,0,1910,\N,58,"Adventure,Drama",3.9,21.0
1191,tt0001203,movie,Excursión al Gombreny,Excursión al Gombreny,0,1910,\N,0,\N,NaN,NaN
1218,tt0001230,movie,Gentleman Joe,Gentleman Joe,0,1910,\N,0,\N,4.8,30.0
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,\N,0,Drama,3.9,22.0
1235,tt0001247,movie,His Brother's Wife,His Brother's Wife,0,1910,\N,0,\N,NaN,NaN
1246,tt0001258,movie,The White Slave Trade,Den hvide slavehandel,0,1910,\N,45,Drama,5.7,139.0
1265,tt0001277,movie,Kapergasten,Kapergasten,0,1910,\N,0,Drama,4.4,24.0
1273,tt0001285,movie,The Life of Moses,The Life of Moses,0,1909,\N,50,"Biography,Drama,Family",5.6,58.0

In [44]:
#Analisando a relação de anos com quantidade de filmes estreados:
juncao['startYear'].value_counts().head(60)

0       76874
2017    18134
2018    18082
2016    17777
2019    17532
2021    16836
2015    16534
2014    15931
2020    15059
2013    14884
2012    14191
2011    13226
2010    12278
2009    11508
2008    10058
2007     8592
2006     7876
2005     7405
2004     6444
2022     6072
2003     5906
2002     5719
2001     5457
2000     5116
1999     4900
1990     4811
1998     4728
1997     4580
1988     4543
1989     4526
1985     4454
1987     4409
1991     4376
1984     4366
1986     4362
1992     4315
1996     4306
1995     4282
1983     4172
1993     4145
1994     4111
1979     4089
1970     4087
1971     4080
1981     4057
1982     4043
1980     4041
1975     4023
1972     3989
1978     3954
1976     3892
1973     3888
1977     3837
1969     3819
1974     3769
1968     3695
1967     3279
1966     3197
1965     3178
1964     2865
Name: startYear, dtype: int64

In [66]:
#Fazendo um tratamento na coluna genres para separar os gêneros:
juncao['genres'] = juncao.apply(lambda x: x['genres'].replace(',',' '), axis=1)

In [48]:
#Separando os gêneros em colunas distintas:
sep = juncao['genres'].str.split(expand=True)

#Visualizar resultado:
sep

                   0          1          2
498               \N       None       None
570           Action  Adventure  Biography
587            Drama       None       None
610            Drama       None       None
625            Drama       None       None
...              ...        ...        ...
8581094  Documentary       None       None
8581121  Documentary       None       None
8581133       Comedy       None       None
8581144           \N       None       None
8581154  Documentary       None       None

[598255 rows x 3 columns]

In [50]:
#Criando tres colunas para os valores do separador, em junção:
juncao[['1','2','3']]= sep

In [51]:
#Visualizar resultado:
juncao

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,1,2,3
498,tt0000502,movie,Bohemios,Bohemios,0,1905,\N,100,\N,4.4,15.0,\N,None,None
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70,Action Adventure Biography,6.1,744.0,Action,Adventure,Biography
587,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907,\N,90,Drama,5.0,17.0,Drama,None,None
610,tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907,\N,0,Drama,4.5,24.0,Drama,None,None
625,tt0000630,movie,Hamlet,Amleto,0,1908,\N,0,Drama,3.9,25.0,Drama,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8581094,tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,0,2015,\N,57,Documentary,NaN,NaN,Documentary,None,None
8581121,tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,0,2007,\N,100,Documentary,NaN,NaN,Documentary,None,None
8581133,tt9916706,movie,Dankyavar Danka,Dankyavar Danka,0,2013,\N,0,Comedy,NaN,NaN,Comedy,None,None
8581144,tt9916730,movie,6 Gunn,6 Gunn,0,2017,\N,116,\N,NaN,NaN,\N,None,None
8581154,tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,0,2013,\N,49,Documentary,NaN,NaN,Documentary,None,None

In [52]:
#Criando uma tabela para cada coluna de gênero junto com as outras colunas:
g1=juncao[['tconst','primaryTitle','titleType','startYear','runtimeMinutes','genres','averageRating','numVotes','1']]
g2=juncao[['tconst','primaryTitle','titleType','startYear','runtimeMinutes','genres','averageRating','numVotes','2']]
g3=juncao[['tconst','primaryTitle','titleType','startYear','runtimeMinutes','genres','averageRating','numVotes','3']]

In [53]:
#Renomeando as colunas responsáveis pelos gêneros para o mesmo nome:
g1.rename(columns={'1':'genero'},inplace=True)
g2.rename(columns={'2':'genero'},inplace=True)
g3.rename(columns={'3':'genero'},inplace=True)

C:\Users\Jump Label\AppData\Local\Temp\ipykernel_18324\3229449583.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1.rename(columns={'1':'genero'},inplace=True)
C:\Users\Jump Label\AppData\Local\Temp\ipykernel_18324\3229449583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2.rename(columns={'2':'genero'},inplace=True)
C:\Users\Jump Label\AppData\Local\Temp\ipykernel_18324\3229449583.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g3.rename(columns={'3':'genero'},inplace=True)

In [54]:
#Fazendo o empilhamento das 3 tabelas:
union = pd.concat([g1,g2,g3])

In [55]:
#Visualizar resultado:
union

,tconst,primaryTitle,titleType,startYear,runtimeMinutes,genres,averageRating,numVotes,genero
498,tt0000502,Bohemios,movie,1905,100,\N,4.4,15.0,\N
570,tt0000574,The Story of the Kelly Gang,movie,1906,70,Action Adventure Biography,6.1,744.0,Action
587,tt0000591,The Prodigal Son,movie,1907,90,Drama,5.0,17.0,Drama
610,tt0000615,Robbery Under Arms,movie,1907,0,Drama,4.5,24.0,Drama
625,tt0000630,Hamlet,movie,1908,0,Drama,3.9,25.0,Drama
...,...,...,...,...,...,...,...,...,...
8581094,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,movie,2015,57,Documentary,NaN,NaN,None
8581121,tt9916680,De la ilusión al desconcierto: cine colombiano...,movie,2007,100,Documentary,NaN,NaN,None
8581133,tt9916706,Dankyavar Danka,movie,2013,0,Comedy,NaN,NaN,None
8581144,tt9916730,6 Gunn,movie,2017,116,\N,NaN,NaN,None
8581154,tt9916754,Chico Albuquerque - Revelações,movie,2013,49,Documentary,NaN,NaN,None

In [62]:
#Agrupando pelo gênero e tirando a média das avaliações e numero de votos de acordo com cada gênero:
media_gen_filmes = union.groupby('genero')[['averageRating','numVotes']].mean().copy().reset_index()

In [64]:
#Retiro o index 28 com os valores nulos e visualizo o resultado:
media_gen_filmes.drop(index=28)

#se for investidor na recomendação ou na criação de filmes ou streams:
#

         genero  averageRating      numVotes
0        Action       5.696818  10952.455884
1         Adult       5.784304     62.335227
2     Adventure       5.877659  14433.479998
3     Animation       6.214753  11289.443217
4     Biography       6.952381   7459.526725
5        Comedy       5.901293   4212.866506
6         Crime       5.979787   7756.904019
7   Documentary       7.211922    314.152579
8         Drama       6.236404   3891.132674
9        Family       6.216035   3978.883390
10      Fantasy       5.905279  10675.084075
11    Film-Noir       6.560236   4543.020997
12    Game-Show       6.800000     15.500000
13      History       6.807785   3777.092760
14       Horror       5.002538   4589.178824
15        Music       6.776028   3077.456201
16      Musical       6.153653   1489.204925
17      Mystery       5.866919   9162.943932
18         News       7.202761    467.127301
19   Reality-TV       5.761905     61.476190
20      Romance       6.085983   3876.498405
21       Sci-Fi       5.298292  18572.677390
22        Short       6.808696    346.739130
23        Sport       6.608065   4875.891439
24    Talk-Show       7.112500     53.125000
25     Thriller       5.572454   7001.794359
26          War       6.419237   3452.967484
27      Western       5.902423   1942.743198

In [60]:
union['genero'].value_counts()

#pq comedia e drama tem mto mais que os outros?

Drama          214771
Documentary    110600
Comedy         101611
\N              71185
Action          50123
Romance         44042
Thriller        40402
Crime           34242
Horror          32965
Adventure       26153
Family          16542
Biography       15735
Mystery         15438
Fantasy         14018
History         13127
Sci-Fi          12752
Music           11074
Musical          9766
War              8906
Adult            8374
Animation        8005
Western          7949
Sport            6361
News             1431
Film-Noir         764
Reality-TV        445
Talk-Show         141
Short              58
Game-Show          20
Name: genero, dtype: int64